credentials:
  users:
    pvenka12:
      email: "sarathvenki@gmail.com"
      name: "pvenka12"
      password: "$2b$12$xxLmyDQvvODQFwiX1u1XL.w1ByhCC5PCrGBRAPtG0wiHw9XRHnAdK"

cookie:
  expiry_days: 9999
  name: "auth_cookie"
  key: "supersecretkey123"